name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t sample-app-ci:latest tasks/ci-cd-pipeline/sample-app

      - name: Save Docker image as artifact
        run: docker save sample-app-ci:latest -o sample-app-ci.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-app-image
          path: sample-app-ci.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: sample-app-image
          path: .

      - name: Load Docker image
        run: docker load -i sample-app-ci.tar

      - name: Run tests inside the container
        run: docker run --rm sample-app-ci:latest pytest -q tests

